# prometheus/prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:5000']

  - job_name: 'user-location-service-1'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['user-location-service-1:5001']

  - job_name: 'user-location-service-2'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['user-location-service-2:5001']

  - job_name: 'ride-payment-service-1'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ride-payment-service-1:5002']

  - job_name: 'ride-payment-service-2'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ride-payment-service-2:5002']

  - job_name: 'redis-shard1'
    static_configs:
      - targets: ['redis-shard1-primary:6379']

  - job_name: 'redis-shard2'
    static_configs:
      - targets: ['redis-shard2-primary:6379']

  - job_name: 'redis-shard3'
    static_configs:
      - targets: ['redis-shard3-primary:6379']
