version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - user-location-service
      - ride-payment-service
      - service-discovery
    environment:
      - SERVICE_DISCOVERY_URL=http://service-discovery:8500
    networks:
      - moldo-net

  ride-payment-service:
    build: ./ride-payment-service
    volumes:
      - ./proto:/usr/src/proto  
    environment:
      - SERVICE_DISCOVERY_URL=http://service-discovery:8500
      - SERVICE_NAME=ride-payment-service
      - SERVICE_ADDRESS=ride-payment-service
      - SERVICE_PORT=50052
    depends_on:
      - service-discovery
      - user-location-service
    ports:
      - "4000:4000"
    networks:
      - moldo-net

  user-location-service:
    build: ./user-location-service
    volumes:
      - ./proto:/usr/src/proto
    ports:
      - "50051:50051"
      - "4001:4001"    # Status endpoint
      - "8080:8080"  
    depends_on:
      - postgres
      - service-discovery
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=userlocationdb
      - SERVICE_DISCOVERY_URL=http://service-discovery:8500
      - SERVICE_NAME=user-location-service
      - SERVICE_ADDRESS=user-location-service
      - SERVICE_PORT=50051
    networks:
      - moldo-net

  service-discovery:
    build: ./service-discovery
    ports:
      - "8500:8500"
    networks:
      - moldo-net

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: userlocationdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - moldo-net

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    networks:
      - moldo-net

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - moldo-net

networks:
  moldo-net:

volumes:
  pgdata:
  mongodata:
  proto:
