version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - nginx
      - service-discovery
    environment:
      - SERVICE_DISCOVERY_URL=http://service-discovery:8500
      - PYTHONUNBUFFERED=1
    networks:
      - moldo-net

  user-location-service-1:
    build: ./user-location-service
    volumes:
      - ./proto:/usr/src/proto
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=userlocationdb
      - SERVICE_DISCOVERY_URL=http://service-discovery:8500
      - SERVICE_NAME=user-location-service
      - SERVICE_ADDRESS=user-location-service-1
      - SERVICE_PORT=5001
    depends_on:
      - postgres
      - service-discovery
    networks:
      - moldo-net

  user-location-service-2:
    build: ./user-location-service
    volumes:
      - ./proto:/usr/src/proto
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=userlocationdb
      - SERVICE_DISCOVERY_URL=http://service-discovery:8500
      - SERVICE_NAME=user-location-service
      - SERVICE_ADDRESS=user-location-service-2
      - SERVICE_PORT=5001
    depends_on:
      - postgres
      - service-discovery
    networks:
      - moldo-net

  ride-payment-service-1:
    build: ./ride-payment-service
    volumes:
      - ./proto:/usr/src/proto
    environment:
      - SERVICE_DISCOVERY_URL=http://service-discovery:8500
      - SERVICE_NAME=ride-payment-service
      - SERVICE_ADDRESS=ride-payment-service-1
      - SERVICE_PORT=5002
      - WEBSOCKET_URLS=ws://user-location-service-1:8021/
    depends_on:
      - service-discovery
      - mongo
    networks:
      - moldo-net

  ride-payment-service-2:
    build: ./ride-payment-service
    volumes:
      - ./proto:/usr/src/proto
    environment:
      - SERVICE_DISCOVERY_URL=http://service-discovery:8500
      - SERVICE_NAME=ride-payment-service
      - SERVICE_ADDRESS=ride-payment-service-2
      - SERVICE_PORT=5002
      - WEBSOCKET_URLS=ws://user-location-service-2:8021/
    depends_on:
      - service-discovery
      - mongo
    networks:
      - moldo-net

  nginx:
    build: ./nginx
    ports:
      - "8080:80"  # Expose Nginx on port 8080
    depends_on:
      - user-location-service-1
      - user-location-service-2
      - ride-payment-service-1
      - ride-payment-service-2
    networks:
      - moldo-net

  service-discovery:
    build: ./service-discovery
    ports:
      - "8500:8500"
    networks:
      - moldo-net

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: userlocationdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - moldo-net

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    networks:
      - moldo-net

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - moldo-net

  prometheus:
      image: prom/prometheus:v2.47.0
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      ports:
        - '9090:9090'
      depends_on:
        - api-gateway
        - user-location-service-1
        - user-location-service-2
        - ride-payment-service-1
        - ride-payment-service-2
      networks:
        - moldo-net
      restart: always

  grafana:
    image: grafana/grafana:10.1.4
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set default admin password
    networks:
      - moldo-net
    restart: always


networks:
  moldo-net:

volumes:
  pgdata:
  mongodata:
  proto:
