# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ride_payment_pb2 as ride__payment__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ride_payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RidePaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PayRide = channel.unary_unary(
                '/RidePaymentService.RidePaymentService/PayRide',
                request_serializer=ride__payment__pb2.PaymentRequest.SerializeToString,
                response_deserializer=ride__payment__pb2.PaymentResponse.FromString,
                _registered_method=True)
        self.ProcessPayment = channel.unary_unary(
                '/RidePaymentService.RidePaymentService/ProcessPayment',
                request_serializer=ride__payment__pb2.ProcessPaymentRequest.SerializeToString,
                response_deserializer=ride__payment__pb2.ProcessPaymentResponse.FromString,
                _registered_method=True)


class RidePaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PayRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RidePaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PayRide': grpc.unary_unary_rpc_method_handler(
                    servicer.PayRide,
                    request_deserializer=ride__payment__pb2.PaymentRequest.FromString,
                    response_serializer=ride__payment__pb2.PaymentResponse.SerializeToString,
            ),
            'ProcessPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPayment,
                    request_deserializer=ride__payment__pb2.ProcessPaymentRequest.FromString,
                    response_serializer=ride__payment__pb2.ProcessPaymentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RidePaymentService.RidePaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RidePaymentService.RidePaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RidePaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PayRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RidePaymentService.RidePaymentService/PayRide',
            ride__payment__pb2.PaymentRequest.SerializeToString,
            ride__payment__pb2.PaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RidePaymentService.RidePaymentService/ProcessPayment',
            ride__payment__pb2.ProcessPaymentRequest.SerializeToString,
            ride__payment__pb2.ProcessPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
